//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costume
    {
        public int Id { get; set; }
        public string Participant { get; set; }
        public string Votes { get; set; }
        public int ParticipantId { get; set; }
        public string Image { get; set; }
    
        public virtual Participant Participant1 { get; set; }
    }
}
